
package weatherairport;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.6-1b01 
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "WeatherAirportWS", targetNamespace = "http://WeatherAirport/", wsdlLocation = "http://localhost:18208/WeatherAirportWS/WeatherAirportWS?wsdl")
public class WeatherAirportWS_Service
    extends Service
{

    private final static URL WEATHERAIRPORTWS_WSDL_LOCATION;
    private final static WebServiceException WEATHERAIRPORTWS_EXCEPTION;
    private final static QName WEATHERAIRPORTWS_QNAME = new QName("http://WeatherAirport/", "WeatherAirportWS");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:18208/WeatherAirportWS/WeatherAirportWS?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        WEATHERAIRPORTWS_WSDL_LOCATION = url;
        WEATHERAIRPORTWS_EXCEPTION = e;
    }

    public WeatherAirportWS_Service() {
        super(__getWsdlLocation(), WEATHERAIRPORTWS_QNAME);
    }

    public WeatherAirportWS_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), WEATHERAIRPORTWS_QNAME, features);
    }

    public WeatherAirportWS_Service(URL wsdlLocation) {
        super(wsdlLocation, WEATHERAIRPORTWS_QNAME);
    }

    public WeatherAirportWS_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, WEATHERAIRPORTWS_QNAME, features);
    }

    public WeatherAirportWS_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WeatherAirportWS_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns WeatherAirportWS
     */
    @WebEndpoint(name = "WeatherAirportWSPort")
    public WeatherAirportWS getWeatherAirportWSPort() {
        return super.getPort(new QName("http://WeatherAirport/", "WeatherAirportWSPort"), WeatherAirportWS.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WeatherAirportWS
     */
    @WebEndpoint(name = "WeatherAirportWSPort")
    public WeatherAirportWS getWeatherAirportWSPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://WeatherAirport/", "WeatherAirportWSPort"), WeatherAirportWS.class, features);
    }

    private static URL __getWsdlLocation() {
        if (WEATHERAIRPORTWS_EXCEPTION!= null) {
            throw WEATHERAIRPORTWS_EXCEPTION;
        }
        return WEATHERAIRPORTWS_WSDL_LOCATION;
    }

}
